global:
  dmodel: &dmodel 64

integrator:
  name: mvn_integrator
  learning_rate: 0.001
  mc_samples: 100
  profile_threshold: 0.01
  load_checkpoint: null
components:

  image_encoder:
    name: mlp_image_encoder
    params:
      depth: 10
      dmodel: *dmodel
      feature_dim: 7
      dropout: null

  metadata_encoder:
    #name: 3d_cnn
    #params:
      #Z: 3
      #H: 21
      #W: 21
      #conv_channels: 64
      #use_norm: true
    name: mlp_metadata_encoder
    params:
      depth: 10
      dmodel: *dmodel
      feature_dim: 7

  profile:
    name: mvn
    params:
      dmodel: 64
      image_shape: [3,21,21]

  decoder:
    name: mvn_decoder
    params:
      mc_samples: 100

  q_bg:
    name: gamma
    params:
      dmodel: 64

  q_I:
    name: gamma
    params:
      dmodel: 64
  #q_I:
    #name: log_normal
    #params:
      #dmodel: 64

  loss:
    name: mvn_loss
    params:

      # Background Priors
      p_bg:
        name: gamma
        params:
          concentration: 1.0
          rate: 1.0
      p_I:
        name: gamma
        params:
          concentration: 0.5
          rate: 0.5

      p_bg_scale: 0.0001
      p_I_scale: 0.0001


data_loader:
  name: default
  params:
    data_dir: "/Users/luis/integratorv3/integrator/data/hewl_816/"
    batch_size: 5
    val_split: 0.3
    test_split: 0.0
    num_workers: 0
    include_test: false
    subset_size: 50
    cutoff: null
    shoebox_features: true
    shoebox_file_names:
      shoeboxes: "weak_standardized_shoeboxes.pt"
      counts: "weak_raw_counts.pt"
      metadata: "weak_metadata.pt"
      masks: "weak_masks.pt"
      shoebox_features: "weak_shoebox_features.pt"

trainer:
  params:
    max_epochs: 20
    accelerator: auto
    devices: 1
    logger: true
    precision: "32"
    check_val_every_n_epoch: 2
    log_every_n_steps: 1
    deterministic: false
    callbacks:
      pred_writer:
        output_dir: null
        write_interval: epoch
    enable_checkpointing: true

output:
  refl_file: "/Users/luis/integratorv3/integrator/data/hewl_816/reflections_.refl"
