mode: polychromatic

integrator:
  name: hierarchical
  args:
    encoder_out: 64
    mc_samples: 100
    predict_keys: [refl_ids, qi_mean, qi_var, qbg_mean, qbg_var,
                  intensity.sum.value, intensity.sum.variance, background.sum.value,
                  background.sum.variance, d, wavelength, group_label, qp_mean]

optimizer:
  lr: 0.001
  lr_schedule: cosine_warmup

data_loader:
  args:
    data_dir: /n/hekstra_lab/people/aldama/integrator_data/hewl_1118/pytorch_data
    batch_size: 2048
    val_split: 0.2

trainer:
  max_epochs: 20
  accelerator: gpu
  devices: 1
  gradient_clip_val: 1.0
