site_name: integrator
site_url: https://hekstra-lab.github.io/integrator/
repo_url: https://github.com/Hekstra-Lab/integrator
repo_name: Hekstra-Lab/integrator
nav:
  - Overview: index.md
  - Getting started:
      - Installation: ./getting-started/installation.md
      - Quickstart: ./getting-started/quickstart.md
      - Configuration: ./getting-started/configuration.md
  - Examples: ./examples/example.md
  - Model:
      - Integrator: ./Model/integrator.md
      - Encoders: ./Model/encoders.md
      - Distributions: ./Model/distributions/distributions.md
theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
    # text: IBM Plex Sans
    #text: Roboto
  #logo: ./assets/intgrater.png
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            docstring_style: google
            merge_init_into_class: true
            extensions:
              - griffe_inherited_docstrings:
                  merge: false
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 6
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
