site_name: Integrator
site_url: https://hekstra-lab.github.io/integrator/
nav: 
    - Home: index.md
    - References:
        - Distributions: references.md
theme: 
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black

plugins: 
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python: 
          options:
            docstring_style: google
            paths: [src]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
