site_name: Integrator
site_url: https://hekstra-lab.github.io/integrator/
nav: 
    - Model:
        - Encoders: ./Model/encoders.md
        - Profiles: ./Model/profiles.md
        - Distributions: ./Model/references.md
theme: 
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black

plugins: 
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python: 
          paths: ["src"]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
