global_vars:
  dmodel: &dmodel 64
  mc_samples: &mc_samples 100
integrator:
  name: integrator_2d
  args:
    mc_samples: *mc_samples
    lr: 0.001
    renyi_scale: 0.0
    h: 21
    w: 21
    weight_decay: 0.0
components:
  encoder1:
    name: shoebox_encoder_2d
    args:
      out_dim: 64
      in_channels: 1
      conv1_out_channels: 64
      conv2_out_channels: 128
      conv1_kernel: [3, 3]
      conv1_padding: [1, 1]
  qp:
    name: dirichlet
    args:
      dmodel: *dmodel
      input_shape: [21, 21]
  qbg:
    name: folded_normal
    args:
      dmodel: *dmodel
      out_features: 2
      use_metarep: false
  qi:
    name: folded_normal
    args:
      dmodel: 64
      out_features: 2
      use_metarep: false
  loss:
    name: loss2
    args:
      pi_name: half_cauchy
      pi_params:
        scale: 1.0
      pbg_name: half_cauchy
      pbg_params:
        scale: 1.0
      pprf_name: dirichlet
      pprf_params:
        concentration: 0.001
      pprf_weight: 0.001
      pbg_weight: 0.5
      pi_weight: 1.0
      use_robust: true
      shape: [1, 21, 21]
      prior_tensor: '/Users/luis/integratorv3/integrator/hewl1118/concentration.pt'
data_loader:
  name: shoebox_data_module_2d
  params:
    data_dir: "/Users/luis/integratorv3/integrator/data/hewl_816/"
    batch_size: 10
    val_split: 0.3
    test_split: 0.0
    num_workers: 0
    include_test: false
    subset_size: 100
    cutoff: 2000
    use_metadata: true
    shoebox_file_names:
      counts: "/Users/luis/integratorv3/integrator/hewl1118/counts_1.pt"
      masks: "/Users/luis/integratorv3/integrator/hewl1118/masks_1.pt"
      stats: "/Users/luis/integratorv3/integrator/hewl1118/stats.pt"
      reference: "/Users/luis/integratorv3/integrator/hewl1118/reference_1.pt"
      standardized_counts: null
trainer:
  params:
    max_epochs: 600
    accelerator: auto
    devices: 1
    logger: true
    precision: "32"
    check_val_every_n_epoch: 2
    log_every_n_steps: 1
    deterministic: false
    callbacks:
      pred_writer:
        output_dir: null
        write_interval: epoch
    enable_checkpointing: true
logger:
  d: 1
  h: 21
  w: 21
output:
  refl_file: "/Users/luis/integratorv3/integrator/hewl1118/tbl_1.refl"
