mode: monochromatic

integrator:
  name: hierarchical
  args:
    data_dim: 3d
    d: 3
    h: 21
    w: 21
    lr: 0.001
    encoder_out: 64
    mc_samples: 100
    predict_keys: default

loss:
  args:
    mc_samples: 100
    eps: 1.0e-06
    n_bins: 25
    profile_prior_scale: 3.0
    pi_weight: 1.0
    pbg_weight: 1.0
    pprf_weight: 1.0

data_loader:
  args:
    data_dir: &data_dir /n/lab_storage/hekstra_lab/people/aldama/integrator_data/hewl_9b7c/pytorch_data
    batch_size: 1024
    val_split: 0.2
    test_split: 0.0
    num_workers: 8
    include_test: true
    shoebox_file_names:
      data_dir: *data_dir
      counts: counts.pt
      masks: masks.pt
      stats: anscombe_stats.pt
      reference: metadata.pt
      standardized_counts: null
    anscombe: true

trainer:
  max_epochs: 40
  accelerator: gpu
  devices: 1
  logger: true
  precision: '32'
  check_val_every_n_epoch: 2
  log_every_n_steps: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
