mode: monochromatic # rotation method monochromatic crystallography

integrator:
  name: hierarchical
  args:
    encoder_out: 64 # hidden representation dimension
    mc_samples: 100 # number of monte carlo samples

optimizer:
  lr: 0.001 # learning rate for the optimizer
  decoder_weight_decay: 1.0e-3 # weight decay for the Adam optimizer

data_loader:
  args:
    data_dir: /n/hekstra_lab/people/aldama/integrator_data/hewl_9b7c/pytorch_data
    batch_size: 2048
    validation_split: 0.2
