"""Compare the single-checkpoint downstream result across stop criteria.

After running each variant (generated by generate_stop_criteria_configs.py)
and running your DIALS/phenix pipeline on each run's best checkpoint,
this script collects the downstream metrics and tabulates them.

Usage:
    uv run python scripts/compare_stop_criteria.py \\
        --runs /n/netscratch/.../wandb/run-*-val_nll_tight \\
               /n/netscratch/.../wandb/run-*-val_nll_loose \\
               /n/netscratch/.../wandb/run-*-train_nll \\
               /n/netscratch/.../wandb/run-*-train_elbo \\
               /n/netscratch/.../wandb/run-*-gap_elbo \\
               /n/netscratch/.../wandb/run-*-no_stop \\
        --out compare_stops.csv

Per run, it:
  * discovers predictions/epoch_XXXX (usually only the best-checkpoint
    epoch under early stopping)
  * parses merged.html, phenix refine log, peaks.csv (same as
    build_correlation_table.py)
  * picks the FINAL epoch present (early-stop runs have ~1; baseline has ~20)
  * reports per run: stopped_at_epoch, peakz_total, cchalf_overall,
    ccanom_overall, r_work_final, r_free_final

Then ranks by peakz_total so you can pick the winning criterion.
"""

import argparse

# Reuse the parsers already written in build_correlation_table.
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from build_correlation_table import (  # type: ignore[import-not-found]
    parse_epoch_dir,
)


def summarize_run(run_dir: Path) -> dict:
    preds = sorted((run_dir / "predictions").glob("epoch_*"))
    if not preds:
        return {"run": run_dir.name, "error": "no predictions/"}

    rows = [r for r in (parse_epoch_dir(d) for d in preds) if r]
    if not rows:
        return {"run": run_dir.name, "error": "no parseable epochs"}

    df = pd.DataFrame(rows).sort_values(by="epoch")  # type: ignore[call-overload]
    final = df.iloc[-1].to_dict()
    final["run"] = run_dir.name
    final["n_epochs_evaluated"] = len(df)
    return final


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--runs", type=Path, nargs="+", required=True)
    p.add_argument("--out", type=Path, default=Path("compare_stops.csv"))
    args = p.parse_args()

    summaries = [summarize_run(r) for r in args.runs]
    df = pd.DataFrame(summaries)

    # Reorder: key columns first, then the rest
    priority = [
        "run",
        "n_epochs_evaluated",
        "epoch",
        "peakz_total",
        "peakz_max",
        "peakz_mean",
        "cchalf_overall",
        "ccanom_overall",
        "r_work_final",
        "r_free_final",
    ]
    priority = [c for c in priority if c in df.columns]
    rest = [c for c in df.columns if c not in priority]
    df = df[priority + rest]

    df = df.sort_values(by="peakz_total", ascending=False).reset_index(
        drop=True
    )  # type: ignore[call-overload]
    df.to_csv(args.out, index=False)
    print(df.to_string(index=False))
    print(f"\nwrote {args.out}")


if __name__ == "__main__":
    main()
