#!/usr/bin/env python
"""Smoke test all 72 model+loss+surrogate+profile combinations.

For each combination:
  1. Build the model via construct_integrator()
  2. Run a forward pass with dummy data
  3. Run backward pass and verify gradients

Usage:
    python scripts/smoke_test_all_combos.py
"""

import sys
import tempfile
import traceback
from copy import deepcopy
from pathlib import Path

import torch
import yaml

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

D, H, W = 3, 21, 21
N_PIXELS = D * H * W  # 1323
ENCODER_OUT = 64
MC_SAMPLES = 4  # small for speed
BATCH_SIZE = 8
N_GROUPS = 10

# Intensity/bg surrogates to test
IBGS = ["gammaA", "gammaB", "gammaC", "gammaD", "folded_normal", "log_normal"]

# Base configs directory (generated by generate_comparison_configs.py)
CONFIG_DIR = Path(__file__).resolve().parent.parent / "configs" / "comparison"

# Models that need group_labels in the loss call
HIERARCHICAL_PREFIXES = ("hierarchicalD_perbin", "hierarchicalD_wilson")

# Physical gaussian surrogate only produces (H*W)-dim profiles,
# incompatible with 3D shoeboxes (D*H*W). Skip these.
SKIP_3D_PHYSICAL = True


# ---------------------------------------------------------------------------
# Dummy data generation
# ---------------------------------------------------------------------------


def create_dummy_data_dir(tmpdir: Path):
    """Create all dummy .pt files needed by losses and surrogates."""
    # Per-group buffers (PerBinLoss / WilsonLoss)
    torch.save(torch.rand(N_GROUPS) + 0.1, tmpdir / "tau_per_group.pt")
    torch.save(torch.rand(N_GROUPS) + 0.1, tmpdir / "bg_rate_per_group.pt")
    torch.save(torch.rand(N_GROUPS) + 0.1, tmpdir / "s_squared_per_group.pt")
    torch.save(
        torch.rand(N_GROUPS, N_PIXELS) + 0.01,
        tmpdir / "concentration_per_group.pt",
    )

    # Physical Gaussian profile basis
    torch.save(
        {
            "basis_type": "physical_gaussian",
            "d": 5,
            "sigma_prior": 1.0,
            "center_base": 10.0,
            "center_scale": 1.5,
            "log_sigma_base": 0.7,
            "width_scale": 0.4,
        },
        tmpdir / "profile_basis.pt",
    )


def make_dummy_batch(is_hierarchical: bool):
    """Create a dummy (counts, shoebox, mask, metadata) batch."""
    counts = torch.randint(0, 50, (BATCH_SIZE, N_PIXELS)).float()
    shoebox = torch.rand(BATCH_SIZE, N_PIXELS)
    mask = torch.ones(BATCH_SIZE, N_PIXELS, dtype=torch.bool)
    metadata = {
        "refl_ids": torch.arange(BATCH_SIZE),
        "is_test": torch.zeros(BATCH_SIZE, dtype=torch.bool),
        "intensity.prf.value": torch.rand(BATCH_SIZE),
        "intensity.prf.variance": torch.rand(BATCH_SIZE),
        "background.mean": torch.rand(BATCH_SIZE),
    }
    if is_hierarchical:
        metadata["group_label"] = torch.randint(0, N_GROUPS, (BATCH_SIZE,))
    return counts, shoebox, mask, metadata


# ---------------------------------------------------------------------------
# Config manipulation
# ---------------------------------------------------------------------------


def patch_config(cfg: dict, tmpdir: str, qi_name: str, qbg_name: str) -> dict:
    """Override data_dir, mc_samples, and qi/qbg surrogate names."""
    cfg = deepcopy(cfg)

    # Point all paths to tmpdir
    cfg["global_vars"]["data_dir"] = tmpdir
    cfg["data_loader"]["args"]["data_dir"] = tmpdir
    cfg["data_loader"]["args"]["shoebox_file_names"]["data_dir"] = tmpdir

    # Small mc_samples for speed
    cfg["integrator"]["args"]["mc_samples"] = MC_SAMPLES
    if "mc_samples" in cfg.get("loss", {}).get("args", {}):
        cfg["loss"]["args"]["mc_samples"] = MC_SAMPLES

    # Swap intensity/bg surrogates
    base_args = {"in_features": ENCODER_OUT, "eps": 1e-5}
    cfg["surrogates"]["qi"] = {"name": qi_name, "args": deepcopy(base_args)}
    cfg["surrogates"]["qbg"] = {"name": qbg_name, "args": deepcopy(base_args)}

    return cfg


# ---------------------------------------------------------------------------
# Single combo test
# ---------------------------------------------------------------------------


def test_combo(
    cfg: dict, label: str, is_hierarchical: bool
) -> tuple[bool, str]:
    """Build model, forward, backward. Returns (passed, error_msg)."""
    from integrator.utils import construct_integrator

    try:
        model = construct_integrator(cfg)
        model.train()

        batch = make_dummy_batch(is_hierarchical)
        counts, shoebox, mask, metadata = batch

        # Forward
        outputs = model(counts, shoebox, mask, metadata)
        forward_out = outputs["forward_out"]

        # Loss
        loss_kwargs = dict(
            rate=forward_out["rates"],
            counts=forward_out["counts"],
            qp=outputs["qp"],
            qi=outputs["qi"],
            qbg=outputs["qbg"],
            mask=forward_out["mask"],
        )
        if is_hierarchical:
            loss_kwargs["group_labels"] = metadata["group_label"].long()
            loss_kwargs["metadata"] = metadata

        loss_dict = model.loss(**loss_kwargs)
        total_loss = loss_dict["loss"]

        # Backward
        total_loss.backward()

        # Verify at least some gradients exist
        has_grad = any(
            p.grad is not None and p.grad.abs().sum() > 0
            for p in model.parameters()
            if p.requires_grad
        )
        if not has_grad:
            return False, "No gradients after backward"

        return True, ""

    except Exception as e:
        return False, f"{type(e).__name__}: {e}\n{traceback.format_exc()}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    # Collect base config files
    config_files = sorted(CONFIG_DIR.glob("*.yaml"))
    if not config_files:
        print(f"ERROR: No configs found in {CONFIG_DIR}")
        print("Run: python scripts/generate_comparison_configs.py first")
        sys.exit(1)

    print(f"Found {len(config_files)} base configs in {CONFIG_DIR}")
    print(
        f"Testing {len(config_files)} x {len(IBGS)} = {len(config_files) * len(IBGS)} combinations\n"
    )

    results = []

    with tempfile.TemporaryDirectory() as tmpdir:
        create_dummy_data_dir(Path(tmpdir))

        for cfg_path in config_files:
            cfg_base = yaml.safe_load(cfg_path.read_text())
            prefix = cfg_path.stem
            is_hier = any(
                prefix.startswith(hp) for hp in HIERARCHICAL_PREFIXES
            )

            for ibg in IBGS:
                label = f"{prefix} | qi={ibg} qbg={ibg}"

                # Physical gaussian is 2D-only — skip for 3D configs
                if SKIP_3D_PHYSICAL and "physical" in prefix and D > 1:
                    results.append(
                        (label, True, "SKIPPED (physical gaussian 2D-only)")
                    )
                    print(f"  [SKIP] {label}  (physical gaussian is 2D-only)")
                    continue

                cfg = patch_config(cfg_base, tmpdir, qi_name=ibg, qbg_name=ibg)

                passed, err = test_combo(cfg, label, is_hier)
                status = "PASS" if passed else "FAIL"
                results.append((label, passed, err))
                print(f"  [{status}] {label}")
                if not passed:
                    # Print first 3 lines of traceback
                    for line in err.strip().split("\n")[:3]:
                        print(f"         {line}")

    # Summary
    n_pass = sum(1 for _, p, _ in results if p)
    n_fail = sum(1 for _, p, _ in results if not p)
    print(f"\n{'=' * 60}")
    print(
        f"RESULTS: {n_pass} passed, {n_fail} failed out of {len(results)} total"
    )
    print(f"{'=' * 60}")

    if n_fail > 0:
        print("\nFailed combos:")
        for label, passed, err in results:
            if not passed:
                print(f"  - {label}")
                for line in err.strip().split("\n")[:5]:
                    print(f"    {line}")
        sys.exit(1)
    else:
        print("\nAll combinations passed!")


if __name__ == "__main__":
    main()
