from integrator.data_loaders import (
    ShoeboxDataModule,
    ShoeboxDataModule2D,
    SimulatedShoeboxLoader,
)
from integrator.model.distributions import (
    BivariateLogNormalSurrogate,
    DirichletDistribution,
    DirichletDistributionB,
    FanoGammaRepamB,
    FanoGammaRepamD,
    FoldedNormalA,
    FoldedNormalDistribution,
    GammaDistribution,
    GammaDistributionRepamA,
    GammaDistributionRepamB,
    GammaDistributionRepamC,
    GammaDistributionRepamD,
    HalfNormalDistribution,
    LinearProfileSurrogate,
    LogisticNormalSurrogate,
    LogNormalA,
    LogNormalDistribution,
    PerBinLogisticNormalSurrogate,
    PhysicalGaussianProfileSurrogate,
    TotalFractionSurrogate,
)
from integrator.model.encoders import (
    BorderPixelMLPEncoder,
    BorderStatsEncoder,
    IntensityEncoder,
    MLPMetadataEncoder,
    ShoeboxEncoder,
)
from integrator.model.integrators import (
    HierarchicalIntegrator,
    HierarchicalIntegratorB,
    HierarchicalIntegratorD,
    IntegratorModelA,
    IntegratorModelB,
    IntegratorModelC,
    IntegratorModelD,
    IntegratorModelE,
    IntegratorModelF,
)
from integrator.model.loss import (
    HierarchicalShoeboxLoss,
    Loss,
    PerBinLoss,
    WilsonPerBinLoss,
)

REGISTRY = {
    "encoders": {
        "shoebox_encoder": ShoeboxEncoder,
        "intensity_encoder": IntensityEncoder,
        "mlp_metadata_encoder": MLPMetadataEncoder,
        "border_pixel_mlp": BorderPixelMLPEncoder,
        "border_stats_encoder": BorderStatsEncoder,
    },
    "loss": {
        "default": Loss,
        "hierarchical_shoebox": HierarchicalShoeboxLoss,
        "per_bin": PerBinLoss,
        "wilson_per_bin": WilsonPerBinLoss,
    },
    "integrator": {
        "modela": IntegratorModelA,
        "modelb": IntegratorModelB,
        "modelc": IntegratorModelC,
        "modeld": IntegratorModelD,
        "modele": IntegratorModelE,
        "modelf": IntegratorModelF,
        "hierarchical": HierarchicalIntegrator,
        "hierarchicalB": HierarchicalIntegratorB,
        "hierarchicalD": HierarchicalIntegratorD,
    },
    "surrogates": {
        "gamma": GammaDistribution,
        "gammaA": GammaDistributionRepamA,
        "gammaB": GammaDistributionRepamB,
        "gammaC": GammaDistributionRepamC,
        "gammaD": GammaDistributionRepamD,
        "fano_gammaB": FanoGammaRepamB,
        "fano_gammaD": FanoGammaRepamD,
        "log_normal": LogNormalDistribution,
        "folded_normal": FoldedNormalDistribution,
        "half_normal": HalfNormalDistribution,
        "dirichlet": DirichletDistribution,
        "dirichletB": DirichletDistributionB,
        "folded_normal_A": FoldedNormalA,
        "log_normal_A": LogNormalA,
        "bivariate_log_normal": BivariateLogNormalSurrogate,
        "linear_profile_surrogate": LinearProfileSurrogate,
        "logistic_normal_surrogate": LogisticNormalSurrogate,
        "per_bin_logistic_normal": PerBinLogisticNormalSurrogate,
        "physical_gaussian_surrogate": PhysicalGaussianProfileSurrogate,
        "total_fraction_surrogate": TotalFractionSurrogate,
    },
    "data_loader": {
        "default": ShoeboxDataModule,
        "shoebox_data_module_2d": ShoeboxDataModule2D,
        "simulated_data": SimulatedShoeboxLoader,
    },
}
