# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - name: Install uv
        run: pip install uv

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: uv-${{ runner.os }}-

      - name: Sync dev env
        run: uv sync --dev

      - name: Lint (ruff)
        run: uv run ruff check .

      # - name: Types (mypy)
      #   run: uv run mypy src/integrator

      - name: Tests (pytest + coverage)
        run: uv run pytest -q --cov=integrator --cov-report=term-missing

      - name: Build (hatchling via build)
        run: uv run python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
